### ISSUE TITLE
Project still active ?

### ISSUE THREAD

**Issue by sashless** [standard-analytics/web-verse#7]
Hey,

i created a fork to add changes quickly. https://github.com/sashless/web-verse/releases/tag/0.3-sashless

What i did was

* stopped adding ID and HASH ( seems unused, any plans for this ?)
* adding a key identifier to the `body` as well in case body is the only parent of a textNode
* removed the whitelist `citeable` and introduced a blacklist ( i need to cite everything except for NOSCRIPT, SCRIPT, STYLE ) 

I would like to push some changes upstream to avoid keeping track of master in upstream, are you still working active on this repository ?

**Comment by sballesteros** [comment]
Hello,

Yes we are still actively working on this repo.

Some comments regarding your changes:

> stopped adding ID and HASH ( seems unused, any plans for this ?)

For the hash (sha1) we use that first before trying to match with the key. A match by sha1 provides a stronger guarantee than a match by key.

> adding a key identifier to the body as well in case body is the only parent of a textNode

Good point. Would happily merge a PR for that.

> removed the whitelist citeable and introduced a blacklist ( i need to cite everything except for NOSCRIPT, SCRIPT, STYLE )

Makes sense. The major caveat by allowing any element to be citeable is that a lot of inline elements (`<em>`, `<strong>`, `<span>` ...) are likely to contain only 1 word and in this case the algorithm makes little sense. Maybe we need to be more flexible here and provide both options (flexible whitelist and flexible blacklist).

**Comment by sashless** [comment]
nice, will file a PR !

RE: hash

okay good to know. I did not found any code which is using the hash. I guess its supposed to be used in a simple selector like `[data-hash=a-b-c]` ?
Beside that i had test cases where `hash` and `key` have been the same for multiple cases. To make it stronger i use the `tagName` of the $scope as well like `p[data-key=AcF]`. Maybe i lookup the parents and include their `key` as well. Any idea to circumvent that ?

**Comment by sashless** [comment]
What makes me curious is when the hash is stronger to guarantee a match why bothering with the key ? 

The method `findKey` seems to be unnecessary as well. In my test cases it had the same result with `findKey` as i would use a simple selector `[data-key=zRda]`.

Have you different test cases ?

In result it seems like the best result is achievable with:

* using `hash` + tagName, called unique selector
* when not unique, do the same with parent and concat the selectors

**Comment by sashless** [comment]
ah well i guess the point with using the `data-key` is when some text was changed the hash will not match anymore but the key might match, right ?

**Comment by sballesteros** [comment]
It really depends if you have control on the document being annotated and if the document can change over time.

If you control the document and it can't change, then it's simple, you can use the `addIdentifiers` method and then match by `data-id`. `data-id` contains universally unique identifier so they will never clash.

If the document can change, then you have to rely on `hash` and `key`. `hash` is stronger in the sense that if the content changes you have the guarantee that the hash will be different. Like you pointed out, `key` has the nice advantage to provide some tolerance to changes. If you haven't already you can watch [this talk](http://2014.jsconf.eu/speakers/michael-donohoe-deeplink-to-anything-on-the-web.html) from Michael Donohoe where he explains how he ended up with the heuristic to compute the keys. In cases when the content may have changed, the `findKey` method is here to help you find a key (that may have changed so you cannot do direct comparison) that is likely to be the right match. The `findKey` method relies on comparing the levenshtein distances between keys.

Last, the nice thing about hash and key is that they can be computed on the fly so it doesn't matter if you don't control the document and can't store those values (as opposed to relying on `id`s). 

Hopefully [this talk](http://2014.jsconf.eu/speakers/michael-donohoe-deeplink-to-anything-on-the-web.html) would do a way better job to clarify all of that!

**Comment by sashless** [comment]
Awesome, thanks for your answers and clarification ! I will file a PR soon regarding the things above :+1:
